MANIFEST_VERSION = 2
MANIFEST_VERSION_KEY = "version"
MANIFEST_BLOCKS_KEY = "blocks"
MANIFEST_GROUPS_KEY = "groups"
MANIFEST_GROUP_KEY = "group_id"
MANIFEST_BOOTSTRAP_KEY = "bootstrap"

FLOAT_PRECISION = 6
